# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('job', models.CharField(default='', max_length=20)),
                ('classmate', models.CharField(default='', max_length=20)),
                ('home', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('life_info', models.TextField(default='', max_length=100)),
                ('job_info', models.TextField(default='', max_length=100)),
                ('classmate_info', models.TextField(default='', max_length=100)),
                ('home_info', models.TextField(default='', max_length=100)),
                ('school_info', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
